name: publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: cargo install --git https://github.com/abissens/elepages.git --branch main
      - run: elepages --destination ./docs --source ./pages --handlebars https://github.com/abissens/blog-template.git -vvv
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "elepages generation"
          git push